### ISSUE TITLE
"ValueError: Sample larger than population or is negative"

### ISSUE THREAD

**Issue by mikel-arbiza** [gsurma/image_generator#1]
Hello,

Really nice work! I get a bug when trying to start Training your model:

"ValueError: Sample larger than population or is negative"

Please could you help?
Thanks in advance

**Comment by gsurma** [comment]
Hi,

My first guess is that `len(input_images) < BATCH_SIZE`.
First of all you have to make sure that you have images in the `INPUT_DATA_DIR`. Then you have to verify if they are properly passed to `input_images`.

**Comment by mikel-arbiza** [comment]
Ok thanks! I’ll have a look at it tomorrow. I’m importing the pictures from Google Drive. I’ll keep you up to date.

--

*Mikel Arbiza.-
{Comunicación Creativa}.
✆ 670270854<tel:670270854> / ☞ www.mikelarbiza.net<http://www.mikelarbiza.net/>

El 13 feb 2019, a las 17:36, Greg <notifications@github.com<mailto:notifications@github.com>> escribió:


Hi,

My first guess is that len(input_images) < BATCH_SIZE.
First of all you have to make sure that you have images in the INPUT_DATA_DIR. Then you have to verify if they are properly passed to input_images.
