### ISSUE TITLE
Graph and samples are empty

### ISSUE THREAD

**Issue by GamerWael** [gsurma/image_generator#6]
Even after 70 epochs, the discriminator/generator graph is empty and my samples are all completely gray.
Epoch 71/300 
Duration: 0.00000 
D Loss: nan 
G Loss: nan

**Comment by kdazzle** [comment]
Hi @WaelShaikh - I'm hitting this one too. Do you remember what the issue might have been? I know it was way long ago.

**Comment by vikasnr** [comment]
@kdazzle @WaelShaikh Any update on this issue? My outputs are greyed out from first iteration.

**Comment by vikasnr** [comment]
Oops! started showing rgbs after few epochs. Looks like parameters we being set.
